= Whide - While IDE
Alaric Whitehead <aw548@sussex.ac.uk>, Supervisor: Dr Bernhard Reus <bernhard@sussex.ac.uk>
1.0, 14 November, 2020
:doctype: article
:icons: font
//Local URL aliases:
:license: ./LICENSE.md
:wiki: ./wiki
//URL aliases:
:chai: https://www.npmjs.com/package/chai
:electron: https://www.electronjs.org/
:git: https://git-scm.com/
:github-ssh: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
:github-ssh-instructions: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
:hwhile: https://github.com/alexj136/HWhile
:mocha: https://www.npmjs.com/package/mocha
:n: https://www.npmjs.com/package/n
:node: https://nodejs.org/en/
:vscode-syntax-highlight: https://github.com/davidpomerenke/while-syntax-vscode
:vuejs: https://vuejs.org/

This is the IDE for DR Reus' WHILE language at link:https://sussex.ac.uk/[The University of Sussex].

[#sect:getting-started]
== Getting Started

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.

[#subsect:prerequisites]
=== Prerequisites

* link:{git}[Git] - for downloading the repository.
+
Preferably with SSH access configured;
see link:{github-ssh}[GitHub's post] about requiring tokens for git operations.
You can set up SSH access using link:{github-ssh-instructions}[these instructions].

* link:{node}[Node.js 12.19 and NPM 6.14] - for running/compiling the code.
+
Once link:{electron}[Electron v12] comes out of beta, Node 14 can be supported here as well.
+
After you have a version of npm installed, I recommend using the link:{n}[`n` package] to manage node/npm versions and updates.

* link:{hwhile}[HWhile] - For running WHILE programs

[#subsect:installing]
=== Installing

. *Clone the repository:*
+
Using SSH:
+
[source]
----
git clone git@github.com:sonrad10/Whide.git
----
+
Or using a username/password:
+
[source]
----
git clone https://github.com/sonrad10/Whide
----

. *Navigate into the cloned directory*
+
[source]
----
cd Whide/
----

. *Optionally, switch to the development branch:*
+
[source]
----
git checkout development
----


. *Install the dependencies*
+
[source]
----
npm install
----

. *Run the program*
+
[source]
----
npm run electron:serve
----

[#subsect:testing]
== Running the tests

Simply run the following command to run the tests:

[source]
----
npm run test
----

Testing is done using the link:{mocha}[mocha] testing framework, and the link:{chai}[chai] assertion library.

[#subsect:deployment]
== Deployment

To compile Whide into an executable file, run:

[source]
----
npm run electron:build
----

This will place the generated executables in the `+dist_electron/+` folder.

[#subsect:program-information]
== Program Information

See the link:{wiki}[wiki] for more detailed information on how the editor works under
the hood.

[#subsect:plugins]
== Installing Plugins

You can find a guide for writing and installing your own plugins in link:{wiki}/Example-Plugins.adoc[the wiki].

[#subsect:buildTools]
== Built With

* Written in link:{node}[Node.js] and link:{https://www.typescriptlang.org/}[TypeScript].

* Interface built with link:{vuejs}[Vue.js].

* Packaged as a desktop app with link:{electron}[Electron]

[#subsect:license]
== License

This project is licensed under the MIT License - see link:{license}[LICENSE.md] file for details.

[#subsect:acknowledgments]
== Acknowledgments

* The code editor is link:{CodeMirror}[CodeMirror].
+
Using syntax highlighting adapted from link:{vscode-syntax-highlight}[David Pomerenke's VS Code Extension].

* The link:{hwhile}[HWhile] interpreter is used to execute the programs.