= Whide - While IDE
:doctype: article
:icons: font
//Maths system
:stem: latexmath
//Local URL aliases:
:license: ./LICENSE.md
:wiki: ./wiki
//URL aliases:
:CodeMirror: https://codemirror.net/
:chai: https://www.npmjs.com/package/chai
:electron: https://www.electronjs.org/
:git: https://git-scm.com/
:github-ssh: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
:github-ssh-instructions: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
:hwhile: https://github.com/alexj136/HWhile
:install-script: https://stackoverflow.com/a/31774097/2966288
:mocha: https://www.npmjs.com/package/mocha
:n: https://www.npmjs.com/package/n
:node: https://nodejs.org/en/
:vscode-syntax-highlight: https://github.com/davidpomerenke/while-syntax-vscode
:vuejs: https://vuejs.org/
:vuetify: https://vuetifyjs.com/

This is the IDE for DR Reus' WHILE language at link:https://sussex.ac.uk/[The University of Sussex].

For information about the WHILE language, see link:WHILE.adoc[] or link:{hwhile}[the HWhile Respository].

== Getting Started

Download the latest program binary for your operating system from the link:https://github.com/sonrad10/Whide/releases[releases page]. These should just work without requiring any other software.

While not required, it is recommended you also install link:https://github.com/alexj136/HWhile[HWhile] to take advantage features such as debugging from within the IDE.

TIP: Whide is also available online at https://sonrad10.github.io/Whide/

NOTE: You won't be able to use HWhile in the web app as that is a desktop application. You may, however, still use While.js for interpreting code.

== TreeLang Quick Reference

=== Overview

In order to display binary trees in a friendlier format, Whide takes advantage of a simple description language.

This language takes a binary tree and a "conversion string" as input and displays the output in a human-readable format.

The language was designed in such a way that it is full compatible with HWhile's syntax.

The language was defined so that any tree input can be itself used as a conversion string.

Any tree which can be displayed by HWhile can be used by this tree language.

Check out the link:https://sonrad10.github.io/Whide/#/trees[Tree Viewer] for a demo of how the language works.

=== Quick Reference

Atoms:

* `nil` - The empty tree
* `any` - Display a tree "as-is"
* `false` `true` - The trees `nil` and `<nil.nil>` respectively
* `bool` `boolean` - Either `true` or `false` (`false|true`)
* `0`, `1`, `2`, ... - The tree representing a specific number
* `int` - any number (`0|1|2|...`)

Modifiers:

* `<Atom.Atom>` - Binary tree
* `Atom[]` - List of `Atom`s
* `[Atom,Atom,Atom]` - List of exactly 3 `Atom`s
* `Atom|Atom` - Accept an atom of these types
* `(Atom|Atom)` - Optional parentheses to specify type bindings

Modifiers can be used to combine atoms to any depth:

* `<int|any.bool>` - A tree where the left element is either a number or a generic tree
* `(bool|int)[]` - Any list of booleans and integers
* `[1, 2, 3, 4]` - Exclusively matches the list `[1,2,3,4]`
* `<int.int>[]` - List of trees where both nodes are numbers
* `int[][]` - A list of lists of numbers

See https://github.com/sonrad10/whide-treeLang for more information and a context free grammar describing the language's syntax.

For information about how the types are defined, see link:WHILE.adoc[].

== Installing (For Developers)

[#subsect:prerequisites]
=== Prerequisites

* link:{git}[Git] - for downloading the repository.
+
Preferably with SSH access configured;
see link:{github-ssh}[GitHub's post] about requiring tokens for git operations.
You can set up SSH access using link:{github-ssh-instructions}[these instructions].

* link:{node}[Node.js 12 and NPM 6] - for running/compiling the code.
+
After you have a version of npm installed, I recommend using the link:{n}[`n` package] to manage node/npm versions and updates.

* (Optional) link:{hwhile}[HWhile] - For running WHILE programs

[#subsect:installing]
=== Installing

. *Clone the repository:*
+
Using SSH:
+
[source]
----
git clone git@github.com:sonrad10/Whide.git
----
+
Or using a username/password:
+
[source]
----
git clone https://github.com/sonrad10/Whide
----

. *Navigate into the cloned directory*
+
[source]
----
cd Whide/
----

. *Optionally, switch to the development branch:*
+
[source]
----
git checkout development
----


. *Install the dependencies*
+
[source]
----
npm install
----

. *Run the program*
+
[source]
----
npm run electron:serve
----

[#subsect:deployment]
== Deployment

To compile Whide into executable binaries, run the following command.
This will place the generated executables in the `+dist_electron/+` folder.

[source]
----
npm run electron:build -- -lmw
----

NOTE: `lmw` stands for **L**inux, **M**ac, and **W**indows; you may remove any of these depending on your desired result.

Additionally, the following command compiles the program into a version that can be hosted by a web server.

[source]
----
npm run build
----

== Building the program icon

The program icons can be generated automatically from an SVG file using the script in the link:icon/[] folder:

[source]
----
#Navigate into the icons folder
cd icon/
#Build the sized icon files
./makeicons.sh
#Replace the program favicon with the new version
cp icon.ico ../public/favicon.ico
----

NOTE: The `+makeicons+` script requires link:https://inkscape.org/[inkscape], link:https://imagemagick.org[imagemagick], and link:https://manpages.ubuntu.com/manpages/hirsute/en/man1/png2icns.1.html[png2icns] to be installed.

[#subsect:buildTools]
== Built With

* Written in link:{node}[Node.js] and link:{https://www.typescriptlang.org/}[TypeScript]

* Interface built with link:{vuejs}[Vue.js] and link:{vuetify}[Vuetify]

* Packaged as a desktop app with link:{electron}[Electron]

[#subsect:license]
== License

This project is licensed under the MIT License - see link:{license}[LICENSE.md] file for details.

[#subsect:acknowledgments]
== Acknowledgments

* The code editor is link:{CodeMirror}[CodeMirror].
+
Using syntax highlighting adapted from link:{vscode-syntax-highlight}[David Pomerenke's VS Code Extension].

* The link:{hwhile}[HWhile] interpreter is used to execute the programs.

* The post-install script to install system plugin dependencies is adapted from link:{install-script}[this StackOverflow answer].